---
- name: get hostnetwork
  command: oc --context {{ cluster.context }} get hostsubnet {{ node }} -o custom-columns=SUBNET:subnet --no-headers
  register: hostsubnet
  
- name: get ip
  command: oc --context {{ cluster.context }} get node {{ node }} -o custom-columns=IP:status.addresses[0].address --no-headers
  register: ip    
   
- name: create node struct
  set_fact:
    node_struct: "{{ {'name': node, 'hostsubnet': hostsubnet.stdout, 'hostname': node, 'ip': ip.stdout} }}"  
    
- name: add node struct
  set_fact:
    cluster_nodes: "{{ cluster_nodes | union( [node_struct] ) }}"    
    
